---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc-nve
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block-nve
