---
- hosts: kube-master
  become: yes
  roles:
  # klovercloud-cluster
     #- nginx-ingress
     #- storage
     #- monitoring
     #- cassandra
     #- cortex
     #- loki
     #- klovercloud
     #- klovercloud_resources
     - klovercloud_services

