[kube-master]
vmi360556.contaboserver.net
[kube-worker]
vmi358328.contaboserver.net
vmi360557.contaboserver.net
[kube-storage]
vmi358328.contaboserver.net
vmi360557.contaboserver.net
[kube-ingress]
vmi358328.contaboserver.net
