[kube_master]
vmi360556.contaboserver.net
[kube_worker]
vmi358328.contaboserver.net
vmi360557.contaboserver.net
[kube_storage]
vmi358328.contaboserver.net
vmi360557.contaboserver.net
[kube_ingress]
vmi358328.contaboserver.net
