[kube-master]
vmi358327.contaboserver.net
[kube-worker]
vmi313424.contaboserver.net
vmi313422.contaboserver.net
[kube-storage]
vmi313424.contaboserver.net
vmi313422.contaboserver.net
[kube-ingress]
vmi313422.contaboserver.net
~
~                            
