ssh kube-master-0 "kubeadm reset -f ; iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X;  rm -rf /etc/kubernetes; rm -rf /var/lib/etcd;  rm -rf $HOME/.kube/config; "
ssh kube-master-1 "kubeadm reset -f ; iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X;  rm -rf /etc/kubernetes; rm -rf /var/lib/etcd;  rm -rf $HOME/.kube/config; "
ssh kube-master-2 "kubeadm reset -f ; iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X;  rm -rf /etc/kubernetes; rm -rf /var/lib/etcd;  rm -rf $HOME/.kube/config;"
ssh skube-worker-0 "kubeadm reset -f ;  iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X"
ssh skube-worker-1 "kubeadm reset -f ;  iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X"
ssh skube-worker-2 "kubeadm reset -f ;  iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X"
ssh skube-storage-0 "kubeadm reset -f ; iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X"
ssh skube-storage-1 "kubeadm reset -f ; iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X"
ssh skube-storage-2 "kubeadm reset -f ; iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X"
ssh skube-ingress-0 "kubeadm reset -f ; iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X"
ssh skube-ingress-1 "kubeadm reset -f ; iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X"
ssh skube-ingress-2 "kubeadm reset -f ; iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X"
