ansible-playbook -i inventory.ini  addon.step.2.cassandra.yaml
ansible-playbook -i inventory.ini  addon.step.3.cortex.yaml
ansible-playbook -i inventory.ini  addon.step.4.loki.yaml
ansible-playbook -i inventory.ini  addon.step.4.promtail.yaml
ansible-playbook -i inventory.ini  addon.step.5.monitoring.yaml 
ansible-playbook -i inventory.ini  addon.step.6.dashboard.yaml 
ansible-playbook -i inventory.ini  addon.step.7.nginx-ingress.yaml
ansible-playbook -i inventory.ini  addon.step.8.cert-manager.yaml 
ansible-playbook -i inventory.ini  addon.step.9.klovercloud-resources.yaml
ansible-playbook -i inventory.ini  addon.step.10.klovercloud-services.yaml
