---

# Create namespaces


- name: Create namespace for klovercloud
  shell: kubectl create ns {{ klovercloud_namespace }};
  when: >
    groups['kube_master'].index(inventory_hostname) == 0 
  ignore_errors: yes

- name: Create namespace for klovercloud-ci 
  shell: kubectl create ns {{ klovercloud_ci_namespace }};
  when: >
    groups['kube_master'].index(inventory_hostname) == 0 
  ignore_errors: yes

- name: Create namespace for nexus 
  shell: kubectl create ns {{ klovercloud_nexus_namespace }};
  when: >
    groups['kube_master'].index(inventory_hostname) == 0 
  ignore_errors: yes

- name: Create namespace for harbor
  shell: kubectl create ns {{ klovercloud_harbor_namespace }};
  when: >
    groups['kube_master'].index(inventory_hostname) == 0 
  ignore_errors: yes

- name: Create namespace for rook ceph
  shell: kubectl create ns {{ klovercloud_rook_ceph_namespace }};
  when: >
    groups['kube_master'].index(inventory_hostname) == 0 
  ignore_errors: yes

- name: reset variables
  set_fact:
    klovercloud_harbor_admin_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
    klovercloud_rook_ceph_object_storage_access_key: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
    klovercloud_rook_ceph_object_storage_secret_key: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
    klovercloud_mongodb_root_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
    klovercloud_super_admin_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"

#  Create directory and cp descriptors

- name: Creates /etc/kubernetes/kubeadm/klovercloud/klovercloud_resources directory
  file: path=/etc/kubernetes/kubeadm/klovercloud/klovercloud_resources  recurse=yes state=directory
  when: >
    groups['kube_master'].index(inventory_hostname) == 0  


- name: Copy descriptors
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
     - { src: 'step.0.1.secrets.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.0.1.secrets.yaml'  }  
     - { src: 'step.0.2.cert_issuer.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.0.2.cert_issuer.yaml'  }
     - { src: 'step.0.3.config_map.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.0.3.config_map.yaml'  }
     - { src: 'step.1.harbor_installation.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.1.harbor_installation.yaml'  }  
     - { src: 'step.2.radosgw_exporter.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.2.radosgw_exporter.yaml'  } 
     - { src: 'step.3.mywebsql.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.3.mywebsql.yaml'  } 
  when: >
    groups['kube_master'].index(inventory_hostname) == 0  

  


# Create secrets

- name: Create secret to pull images from registry for tekton ns
  shell: kubectl create secret docker-registry  {{ klovercloud_image_pulling_secret }} --docker-server={{ klovercloud_registry_url }} --docker-username={{ klovercloud_registry_username }} --docker-password={{ klovercloud_registry_password }} --docker-email={{ klovercloud_registry_email }} -n {{ klovercloud_ci_namespace }};
  when: >
    groups['kube_master'].index(inventory_hostname) == 0   
  ignore_errors: yes

- name: Create secret to pull images from registry klovercloud ns
  shell: kubectl create secret docker-registry  {{ klovercloud_image_pulling_secret }} --docker-server={{ klovercloud_registry_url }} --docker-username={{ klovercloud_registry_username }} --docker-password={{ klovercloud_registry_password }} --docker-email={{ klovercloud_registry_email }} -n {{ klovercloud_namespace }};
  when: >
    groups['kube_master'].index(inventory_hostname) == 0   
  ignore_errors: yes

- name: Create secret to pull images from registry klovercloud ns
  shell: kubectl create secret docker-registry  {{ klovercloud_image_pulling_secret }} --docker-server={{ klovercloud_registry_url }} --docker-username={{ klovercloud_registry_username }} --docker-password={{ klovercloud_registry_password }} --docker-email={{ klovercloud_registry_email }} -n {{ klovercloud_harbor_namespace }};
  when: >
    groups['kube_master'].index(inventory_hostname) == 0   
  ignore_errors: yes 

- name: Creates secrets if not present
  shell: kubectl get secret {{ klovercloud_mongodb_secret }} -n {{ klovercloud_ci_namespace }} -o json || kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.0.1.secrets.yaml;
  when: >
    groups['kube_master'].index(inventory_hostname) == 0   
  ignore_errors: yes

# Deploy configMap

- name: Creates configMap
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.0.3.config_map.yaml;
  when: >
    groups['kube_master'].index(inventory_hostname) == 0   
  ignore_errors: yes

# Create issuer

- name: Create issuer
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.0.2.cert_issuer.yaml;
  when: >
    groups['kube_master'].index(inventory_hostname) == 0 

# install tekton

- name: Install Tekton Pipelines and its dependencies
  shell: kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml;
  when: >
   groups['kube_master'].index(inventory_hostname) == 0   
  ignore_errors: yes

- name: Run for those container runtime that does not support image-reference:tag@digest
  shell: kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.notags.yaml;
  when: >
   groups['kube_master'].index(inventory_hostname) == 0   
  ignore_errors: yes


# Install harbor

- name: Install harbor
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.1.harbor_installation.yaml;
  when: >
    groups['kube_master'].index(inventory_hostname) == 0
  ignore_errors: yes


- name: 
  wait_for:
    timeout: 20

# deploy radosgw exporter

 
- name: deploy radosgw exporter
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.2.radosgw_exporter.yaml;
  when: >
    groups['kube_master'].index(inventory_hostname) == 0   

# deploy mywebsql
 
- name: deploy mywebsql
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.3.mywebsql.yaml;
  when: >
    groups['kube_master'].index(inventory_hostname) == 0   



