---

# Create namespaces


- name: Create namespace for klovercloud
  shell: kubectl create ns {{ klovercloud_namespace }};
  when: >
    groups['kube-master'].index(inventory_hostname) == 0 
  ignore_errors: yes

- name: Create namespace for klovercloud-ci 
  shell: kubectl create ns {{ klovercloud_ci_namespace }};
  when: >
    groups['kube-master'].index(inventory_hostname) == 0 
  ignore_errors: yes

- name: Create namespace for nexus 
  shell: kubectl create ns {{ klovercloud_nexus_namespace }};
  when: >
    groups['kube-master'].index(inventory_hostname) == 0 
  ignore_errors: yes

- name: Create namespace for harbor
  shell: kubectl create ns {{ klovercloud_harbor_namespace }};
  when: >
    groups['kube-master'].index(inventory_hostname) == 0 
  ignore_errors: yes


- name: Create namespace for rook ceph
  shell: kubectl create ns {{ klovercloud_rook_ceph_namespace }};
  when: >
    groups['kube-master'].index(inventory_hostname) == 0 
  ignore_errors: yes

# reset facts values

- name: reset variables
  set_fact:
    klovercloud_harbor_admin_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
    klovercloud_harbor_postgresql_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
    klovercloud_harbor_clair_db_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
    klovercloud_rook_ceph_object_storage_access_key: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
    klovercloud_rook_ceph_object_storage_secret_key: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
    klovercloud_mongodb_root_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
    klovercloud_super_admin_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"




# copy decriptors

- name: Creates /etc/kubernetes/kubeadm directory
  file: path=/etc/kubernetes/kubeadm/klovercloud/klovercloud_resources  recurse=yes state=directory
  when: >
    groups['kube-master'].index(inventory_hostname) == 0  

# temp=$(kubectl get secret regcred-dh -n tekton -o json | jq -r '.data.".dockerconfigjson"' )

- name: Copy descriptors
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
     - { src: 'step.0.1.secrets.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.0.1.secrets.yaml'  }  
     - { src: 'step.0.2.cert_issuer.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.0.2.cert_issuer.yaml'  }
     - { src: 'step.1.harbor_installation.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.1.harbor_installation.yaml'  } 
     - { src: 'step.2.mongodb.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.2.mongodb.yaml'  }  
     - { src: 'step.3.0.nexus_operator.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.3.0.nexus_operator.yaml'  } 
     - { src: 'step.3.1.nexus.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.3.1.nexus.yaml'  } 
     - { src: 'step.4.kafka.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.4.kafka.yaml'  } 
     - { src: 'step.5.radosgw_exporter.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.5.radosgw_exporter.yaml'  } 
  when: >
    groups['kube-master'].index(inventory_hostname) == 0  
  register: result
  


# Create secrets

- name: Create secret to pull images from registry for tekton ns
  shell: kubectl create secret docker-registry  {{ klovercloud_image_pulling_secret }} --docker-server={{ klovercloud_registry_url }} --docker-username={{ klovercloud_registry_username }} --docker-password={{ klovercloud_registry_password }} --docker-email={{ klovercloud_registry_email }} -n {{ klovercloud_ci_namespace }};
  when: >
    groups['kube-master'].index(inventory_hostname) == 0   
  ignore_errors: yes

- name: Create secret to pull images from registry klovercloud ns
  shell: kubectl create secret docker-registry  {{ klovercloud_image_pulling_secret }} --docker-server={{ klovercloud_registry_url }} --docker-username={{ klovercloud_registry_username }} --docker-password={{ klovercloud_registry_password }} --docker-email={{ klovercloud_registry_email }} -n {{ klovercloud_namespace }};
  when: >
    groups['kube-master'].index(inventory_hostname) == 0   
  ignore_errors: yes

- name: Create secret to pull images from registry klovercloud ns
  shell: kubectl create secret docker-registry  {{ klovercloud_image_pulling_secret }} --docker-server={{ klovercloud_registry_url }} --docker-username={{ klovercloud_registry_username }} --docker-password={{ klovercloud_registry_password }} --docker-email={{ klovercloud_registry_email }} -n {{ klovercloud_harbor_namespace }};
  when: >
    groups['kube-master'].index(inventory_hostname) == 0   
  ignore_errors: yes 

- name: Creates secrets if not present
  shell: kubectl get secret {{ klovercloud_super_admin_secret }} -n {{ klovercloud_namespace }} -o json || /etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.0.1.secrets.yaml;
  when: >
    groups['kube-master'].index(inventory_hostname) == 0   
  ignore_errors: yes

# Create issuer

- name: Create issuer
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.0.2.cert_issuer.yaml;
  when: >
    groups['kube-master'].index(inventory_hostname) == 0 

# install tekton

- name: Install Tekton Pipelines and its dependencies
  shell: kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml;
  when: >
   groups['kube-master'].index(inventory_hostname) == 0   
  ignore_errors: yes

- name: Run for those container runtime that does not support image-reference:tag@digest
  shell: kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.notags.yaml;
  when: >
   groups['kube-master'].index(inventory_hostname) == 0   
  ignore_errors: yes


# Install harbor

- name: Install harbor
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.1.harbor_installation.yaml;
  when: >
    groups['kube-master'].index(inventory_hostname) == 0



- name: 
  wait_for:
    timeout: 20

# deploy mongo db 

- name: deploy mongo db  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.2.mongodb.yaml;
  when: >
    groups['kube-master'].index(inventory_hostname) == 0   

- name: 
  wait_for:
    timeout: 10

# deploy nexus 


- name:  deploy nexus operator deployment descriptor
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.3.0.nexus_operator.yaml;
  when: >
    groups['kube-master'].index(inventory_hostname) == 0   



- name: wait for pods to come up
  shell: kubectl get pods -n {{ klovercloud_nexus_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  ignore_errors: yes

- name: 
  wait_for:
    timeout: 60

- name: wait for pods to get ready
  shell: kubectl wait --for=condition=ready -l "name={{ klovercloud_nexus_operator_name }}" -n {{ klovercloud_nexus_namespace }}
  register: kubectl_get_pods

- name: 
  wait_for:
    timeout: 30

- name:  deploy nexus
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.3.1.nexus.yaml;
  when: >
    groups['kube-master'].index(inventory_hostname) == 0


- name: wait for pods to come up
  shell: kubectl get pods -n {{ klovercloud_nexus_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  ignore_errors: yes

- name: 
  wait_for:
    timeout: 90

- name: wait for pods to come up
  shell: kubectl get pods -n {{ klovercloud_nexus_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]

- name: copy admin.password file from pod
  shell: kubectl cp {{klovercloud_nexus_cr}}-0:/nexus-data/admin.password /etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/admin.password -n nexus


- name: 
  set_fact:
    klovercloud_nexus_default_super_admin_password: "{{ lookup('file', '/etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/admin.password') }}"


- name: Request to reset admin pass of nexus
  shell: kubectl -n {{ klovercloud_nexus_namespace }} exec -it $(kubectl -n {{ klovercloud_nexus_namespace }} get pod -l "app={{ klovercloud_nexus_app_label }}" -o jsonpath='{.items[0].metadata.name}') -- bash -c "curl -u admin:{{ klovercloud_nexus_default_super_admin_password }} -X PUT 'http://localhost:{{ klovercloud_nexus_operator_service_port }}/service/rest/beta/security/users/admin/change-password' -H 'Content-Type:text/plain'  --data-raw admin"
  ignore_errors: yes

# deploy Kafka

- name: deploy Kafka
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.4.kafka.yaml;
  when: >
    groups['kube-master'].index(inventory_hostname) == 0   

- name: wait for pods to come up
  shell: kubectl get pods -l app={{ klovercloud_kafka_app_label }} -n {{ klovercloud_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  ignore_errors: yes

- name: sleep 20 seconds
  wait_for:
    timeout: 20

- name: wait for pods to come up
  shell:  kubectl get pods -l app={{ klovercloud_kafka_app_label }} -n {{ klovercloud_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]


# deploy radosgw exporter

 
- name: deploy radosgw exporter
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_resources/step.5.radosgw_exporter.yaml;
  when: >
    groups['kube-master'].index(inventory_hostname) == 0   


