---

- name: Install Tekton Pipelines and its dependencies
  shell: kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml;
  when: >
    inventory_hostname == "kube-master-0" 
  ignore_errors: yes

- name: Run for those container runtime that does not support image-reference:tag@digest
  shell: kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.notags.yaml;
  when: >
    inventory_hostname == "kube-master-0" 
  ignore_errors: yes

- name: Create namespace for klovercloud
  shell: kubectl create ns {{ klovercloud_namespace }};
  when: >
    inventory_hostname == "kube-master-0" 
  ignore_errors: yes

- name: Create namespace for klovercloud-ci 
  shell: kubectl create ns {{ klovercloud_ci_namespace }};
  when: >
    inventory_hostname == "kube-master-0" 
  ignore_errors: yes

- name: Create namespace for nexus 
  shell: kubectl create ns {{ klovercloud_nexus_namespace }};
  when: >
    inventory_hostname == "kube-master-0" 
  ignore_errors: yes

- name: Create namespace for harbor
  shell: kubectl create ns {{ klovercloud_harbor_namespace }};
  when: >
    inventory_hostname == "kube-master-0" 
  ignore_errors: yes


- name: Create secret to pull klovercloud-ci and generator images from harbor
  shell: kubectl create secret docker-registry  {{ klovercloud_image_pulling_secret }} --docker-server={{ klovercloud_registry_url }} --docker-username={{ klovercloud_registry_username }} --docker-password={{ klovercloud_registry_password }} --docker-email={{ klovercloud_registry_email }} -n {{ klovercloud_ci_namespace }};
  when: >
    inventory_hostname == "kube-master-0" 
  ignore_errors: yes

- name: reset klovercloud_harbor_admin_password, klovercloud_harbor_postgresql_password and klovercloud_harbor_clair_db_password
  set_fact:
    klovercloud_harbor_admin_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
    klovercloud_harbor_postgresql_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
    klovercloud_harbor_clair_db_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"


- name: Creates /etc/kubernetes/kubeadm directory
  file: path=/etc/kubernetes/kubeadm/klovercloud/prerequisites  recurse=yes state=directory
  when: >
    inventory_hostname == "kube-master-0"


- name: Copy harbor installation, klovercloud-harbor and mongodb descriptors
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
     - { src: 'step.0.harbor_installation.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/prerequisites/step.0.harbor_installation.yaml'  } 
     - { src: 'step.0.1.klovercloud-harbor.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/prerequisites/step.0.1.klovercloud-harbor.yaml'  } 
     - { src: 'step.1.mongodb.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/apps/step.1.mongodb.yaml'  } 
  when: >
    inventory_hostname == "kube-master-0"
  register: result

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/prerequisites/step.0.harbor_installation.yaml;
  when: >
    inventory_hostname == "kube-master-0" 


- name: wait for pods to come up
  shell: kubectl get pods -n {{ klovercloud_harbor_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]


- name: reset klovercloud_harbor_admin_auth_token
  set_fact:
    klovercloud_harbor_admin_auth_token: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/prerequisites/step.0.1.klovercloud-harbor.yaml;
  when: >
    inventory_hostname == "kube-master-0" 


- name: wait for pods to come up
  shell: kubectl get pods -n {{ klovercloud_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]

- name: 
  wait_for:
    timeout: 30

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/prerequisites/step.1.mongodb.yaml;
  when: >
    inventory_hostname == "kube-master-0" 

- name: wait for pods to come up
  shell: kubectl get pods -n {{ klovercloud_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]

- name: 
  wait_for:
    timeout: 30
    
- name: Creates /etc/kubernetes/kubeadm directory
  file: path=/etc/kubernetes/kubeadm/klovercloud/apps  recurse=yes state=directory
  when: >
    inventory_hostname == "kube-master-0"

- name: Copy klobercloud-ci,kafka,nexus,admin-secret descriptors
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
     - { src: 'step.2.klovercloud-ci.v1.1.0.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/apps/step.2.klovercloud-ci.v1.1.0.yaml'  } 
     - { src: 'step.3.kafka.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/apps/step.3.kafka.yaml'  } 
     - { src: 'step.4.nexus.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/apps/step.4.nexus.yaml'  } 
     - { src: 'step.5.admin_secret.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/apps/step.5.admin_secret.yaml'  } 
     
  when: >
    inventory_hostname == "kube-master-0"
  register: result

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/apps/;
  when: >
    inventory_hostname == "kube-master-0" 



- name: Copy cert-issuer descriptor
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
     - { src: 'step.6.cert_issuer.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/apps/step.6.cert_issuer.yaml'  } 
     
  when: >
    inventory_hostname == "kube-master-0"
  register: result

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/apps/step.6.cert_issuer.yaml;
  when: >
    inventory_hostname == "kube-master-0" 


- name: reset klovercloud_super_admin_username and klovercloud_super_admin_password
  set_fact:
    klovercloud_super_admin_username: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
    klovercloud_super_admin_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"



- name: Copy listener descriptor
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
     - { src: 'step.7.listener.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/apps/step.7.listener.yaml'  } 
     
  when: >
    inventory_hostname == "kube-master-0"
  register: result

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/apps/step.7.listener.yaml;
  when: >
    inventory_hostname == "kube-master-0" 

- name: 
  wait_for:
    timeout: 30

- name: Login to listener service as admin user
  uri:
    url: http://{{klovercloud_listener_ingress_host}}/api/auth/login
    method: POST
    return_content: yes
    status_code: 200
    body_format: json
    headers:
      Content-Type: "application/json"
    body: "{ \"username\": \"{{ klovercloud_super_admin_username }}\",\"password\": \"{{ klovercloud_super_admin_password }}\"}" 
  register: login_result
  until: login_result.json.success == true
  retries: 10
  delay: 10

- name: Create an API Access Token when login request returns token
  uri:
    url: http://{{klovercloud_listener_ingress_host}}/api/api-access-token
    method: POST
    return_content: yes
    status_code: 200
    body_format: json
    headers:
      Content-Type: "application/json"
      x-auth-token: login_result.json.token
  register: api_access_token
  when: login_result.json.success == true


- name: reset klovercloud_api_access_token
  set_fact:
    klovercloud_api_access_token: api_access_token.json.data
  when: api_access_token.json.success == true
  

- name: Copy management descriptor
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
     - { src: 'step.8.management.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/apps/step.8.management.yaml'  } 
     
  when: >
    inventory_hostname == "kube-master-0"
  register: result

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/apps/step.8.management.yaml;
  when: >
    inventory_hostname == "kube-master-0" 




- name: wait for pods to come up
  shell: kubectl get pods -n {{ klovercloud_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]

- name: 
  wait_for:
    timeout: 10
    


- name: Copy facade descriptor
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
     - { src: 'step.9.facade.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/apps/step.9.facade.yaml'  } 
     
  when: >
    inventory_hostname == "kube-master-0"
  register: result

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/apps/step.9.facade.yaml;
  when: >
    inventory_hostname == "kube-master-0" 


- name: wait for pods to come up
  shell: kubectl get pods -n {{ klovercloud_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]



- name: Login to facade service as super admin user
  uri:
    url: https://{{klovercloud_facade_host}}/api/auth/login
    method: POST
    return_content: yes
    status_code: 200
    body_format: json
    headers:
      Content-Type: "application/json" 
    body: "{ \"username\": \"{{ klovercloud_super_admin_username }}\",\"password\": \"{{ klovercloud_super_admin_password }}\"}"
  register: facade_login_result
  until: facade_login_result.json.success == true
  retries: 10
  delay: 10

- name: Request to create a Service User using facade login token
  uri:
    url: http://{{klovercloud_facade_host}}/api/user
    method: POST
    return_content: yes
    status_code: 200
    body_format: json
    headers:
      Content-Type: "application/json"
      x-auth-token: facade_login_result.json.token
    body: "{ \"firstName\": \"{{klovercloud_service_firstname}}\",\"lastName\": \"{{klovercloud_service_lastname}}\",\"username\": \"{{ klovercloud_service_username }}\",\"userType\": \"{{ klovercloud_service_usertype }}\",\"authorities\": [ \"ROLE_AGENT_SERVICE\"]}"
  register: service_user
  when: facade_login_result.json.success == true

- name: Request to create a facade Service access token
  uri:
    url:  http://{{klovercloud_facade_host}}/api/api-access-token
    method: POST
    return_content: yes
    status_code: 200
    body_format: json
    headers:
      Content-Type: "application/json"
      x-auth-token: facade_login_result.json.token
    body:  "{ \"userId\": \"{{ service_user.json.data }}\"}" 
  register: facade_api_access_token
  when: service_user.json.success == true

- name: reset klovercloud_facade_api_access_token
  set_fact:
    klovercloud_facade_api_access_token: facade_api_access_token.json.data
  when: facade_api_access_token.json.success == true
  
- name: wait for pods to come up
  shell: kubectl get pods -n {{ klovercloud_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]


- name: Copy pipeline descriptor
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
     - { src: 'step.10.pipeline.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/apps/step.10.pipeline.yaml'  } 
     
  when: >
    inventory_hostname == "kube-master-0"
  register: result

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/apps/step.10.pipeline.yaml;
  when: >
    inventory_hostname == "kube-master-0" 


- name: copy admin.password file from pod
  shell: kubectl cp {{klovercloud_nexus_cr}}-0:/nexus-data/admin.password /etc/kubernetes/kubeadm/klovercloud/apps/admin.password -n nexus



- name: 
  set_fact:
    klovercloud_nexus_default_super_admin_password: "{{ lookup('file', '/etc/kubernetes/kubeadm/klovercloud/apps/admin.password') }}"

- name: Request to reset admin pass of nexus
  uri:
    url: http://{{klovercloud_nexus_ingress_host}}/service/rest/beta/security/users/{{klovercloud_nexus_super_admin}}/change-password
    method: PUT
    return_content: yes
    status_code: 200
    body_format: json
    headers:
      Content-Type: "text/plain"
      Authorization: "Basic {{klovercloud_nexus_default_super_admin_password}}"
    body: "{{klovercloud_nexus_super_admin_password}}"


- name: Copy monitoring and database service descriptor
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
     - { src: 'step.11.monitor.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/apps/step.11.monitor.yaml'  } 
     - { src: 'step.12.klovercloud-database.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/apps/step.12.klovercloud-database.yaml'  } 
  when: >
    inventory_hostname == "kube-master-0"
  register: result

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/apps/step.11.monitor.yaml;
  when: >
    inventory_hostname == "kube-master-0" 

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/apps/step.12.klovercloud-database.yaml;
  when: >
    inventory_hostname == "kube-master-0" 

  # clone generator repos 
  # build generator images 
  # push to harbor 
  # Change nexus username and password




