{
 "title": "Host Details",
 "tags": [ "overview" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "ceph_hosts",
    "label": "Hostname",
    "query": "label_values(node_scrape_collector_success, instance) "
   }
  ]
 },
 "panels": [
  { "title": "$ceph_hosts System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OSDs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (ceph_daemon) (ceph_osd_metadata{hostname='$ceph_hosts'}))"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "Shows the CPU breakdown. When multiple servers are selected, only the first host's cpu data is shown",
   "gridPos": { "h": 10, "w": 6, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "% Utilization" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (\n  irate(node_cpu{instance=~\"($ceph_hosts).*\", mode=~\"(irq|nice|softirq|steal|system|user|iowait)\"}[1m]) or\n  irate(node_cpu_seconds_total{instance=~\"($ceph_hosts).*\", mode=~\"(irq|nice|softirq|steal|system|user|iowait)\"}[1m])\n) / scalar(\n  sum(irate(node_cpu{instance=~\"($ceph_hosts).*\"}[1m]) or\n      irate(node_cpu_seconds_total{instance=~\"($ceph_hosts).*\"}[1m]))\n) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "bytes", "label": "RAM used" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal{instance=~\"[[ceph_hosts]].*\"} or node_memory_MemTotal_bytes{instance=~\"[[ceph_hosts]].*\"})- (\n  (node_memory_MemFree{instance=~\"[[ceph_hosts]].*\"} or node_memory_MemFree_bytes{instance=~\"[[ceph_hosts]].*\"})  + \n  (node_memory_Cached{instance=~\"[[ceph_hosts]].*\"} or node_memory_Cached_bytes{instance=~\"[[ceph_hosts]].*\"}) + \n  (node_memory_Buffers{instance=~\"[[ceph_hosts]].*\"} or node_memory_Buffers_bytes{instance=~\"[[ceph_hosts]].*\"}) +\n  (node_memory_Slab{instance=~\"[[ceph_hosts]].*\"} or node_memory_Slab_bytes{instance=~\"[[ceph_hosts]].*\"})\n  )\n  \n",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_MemFree{instance=~\"[[ceph_hosts]].*\"} or node_memory_MemFree_bytes{instance=~\"[[ceph_hosts]].*\"} ",
     "legendFormat": "Free"
    },
    {
     "expr": "(node_memory_Cached{instance=~\"[[ceph_hosts]].*\"} or node_memory_Cached_bytes{instance=~\"[[ceph_hosts]].*\"}) + \n(node_memory_Buffers{instance=~\"[[ceph_hosts]].*\"} or node_memory_Buffers_bytes{instance=~\"[[ceph_hosts]].*\"}) +\n(node_memory_Slab{instance=~\"[[ceph_hosts]].*\"} or node_memory_Slab_bytes{instance=~\"[[ceph_hosts]].*\"}) \n",
     "legendFormat": "buffers/cache"
    },
    {
     "expr": "node_memory_MemTotal{instance=~\"[[ceph_hosts]].*\"} or node_memory_MemTotal_bytes{instance=~\"[[ceph_hosts]].*\"} ",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Network Load",
   "type": "graph",
   "description": "Show the network load (rx,tx) across all interfaces (excluding loopback 'lo')",
   "gridPos": { "h": 10, "w": 6, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "decbytes", "label": "Send (-) / Receive (+)" }
   ],
   "targets": [
    {
     "expr": "sum by (device) (\n  irate(node_network_receive_bytes{instance=~\"($ceph_hosts).*\",device!=\"lo\"}[1m]) or \n  irate(node_network_receive_bytes_total{instance=~\"($ceph_hosts).*\",device!=\"lo\"}[1m])\n)",
     "legendFormat": "{{device}}.rx"
    },
    {
     "expr": "sum by (device) (\n  irate(node_network_transmit_bytes{instance=~\"($ceph_hosts).*\",device!=\"lo\"}[1m]) or\n  irate(node_network_transmit_bytes_total{instance=~\"($ceph_hosts).*\",device!=\"lo\"}[1m])\n)",
     "legendFormat": "{{device}}.tx"
    }
   ]
  },
  {
   "title": "Network drop rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "yaxes": [
    { "format": "pps", "label": "Send (-) / Receive (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_drop{instance=~\"[[ceph_hosts]].*\"}[1m]) or irate(node_network_receive_drop_total{instance=~\"[[ceph_hosts]].*\"}[1m])",
     "legendFormat": "{{device}}.rx"
    },
    {
     "expr": "irate(node_network_transmit_drop{instance=~\"[[ceph_hosts]].*\"}[1m]) or irate(node_network_transmit_drop_total{instance=~\"[[ceph_hosts]].*\"}[1m])",
     "legendFormat": "{{device}}.tx"
    }
   ]
  },
  {
   "title": "Raw Capacity",
   "type": "singlestat",
   "description": "Each OSD consists of a Journal/WAL partition and a data partition. The RAW Capacity shown is the sum of the data partitions across all OSDs on the selected OSD hosts.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes and on (ceph_daemon) ceph_disk_occupation{instance=~\"($ceph_hosts).*\"})"
    }
   ]
  },
  {
   "title": "Network error rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "yaxes": [
    { "format": "pps", "label": "Send (-) / Receive (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs{instance=~\"[[ceph_hosts]].*\"}[1m]) or irate(node_network_receive_errs_total{instance=~\"[[ceph_hosts]].*\"}[1m])",
     "legendFormat": "{{device}}.rx"
    },
    {
     "expr": "irate(node_network_transmit_errs{instance=~\"[[ceph_hosts]].*\"}[1m]) or irate(node_network_transmit_errs_total{instance=~\"[[ceph_hosts]].*\"}[1m])",
     "legendFormat": "{{device}}.tx"
    }
   ]
  },
  {
   "title": "OSD Disk Performance Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "$ceph_hosts Disk IOPS",
   "type": "graph",
   "description": "For any OSD devices on the host, this chart shows the iops per physical device. Each device is shown by it's name and corresponding OSD id value",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "(irate(node_disk_writes_completed{instance=~\"($ceph_hosts).*\"}[5m]) or irate(node_disk_writes_completed_total{instance=~\"($ceph_hosts).*\"}[5m])) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\")",
     "legendFormat": "{{device}}({{ceph_daemon}}) writes"
    },
    {
     "expr": "(irate(node_disk_reads_completed{instance=~\"($ceph_hosts).*\"}[5m]) or irate(node_disk_reads_completed_total{instance=~\"($ceph_hosts).*\"}[5m])) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\")",
     "legendFormat": "{{device}}({{ceph_daemon}}) reads"
    }
   ]
  },
  {
   "title": "$ceph_hosts Throughput by Disk",
   "type": "graph",
   "description": "For OSD hosts, this chart shows the disk bandwidth (read bytes/sec + write bytes/sec) of the physical OSD device. Each device is shown by device name, and corresponding OSD id",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "label_replace((irate(node_disk_bytes_written{instance=~\"($ceph_hosts).*\"}[5m]) or irate(node_disk_written_bytes_total{instance=~\"($ceph_hosts).*\"}[5m])), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\") * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\")",
     "legendFormat": "{{device}}({{ceph_daemon}}) write"
    },
    {
     "expr": "label_replace((irate(node_disk_bytes_read{instance=~\"($ceph_hosts).*\"}[5m]) or irate(node_disk_read_bytes_total{instance=~\"($ceph_hosts).*\"}[5m])), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\") * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\")",
     "legendFormat": "{{device}}({{ceph_daemon}}) read"
    }
   ]
  },
  {
   "title": "$ceph_hosts Disk Latency",
   "type": "graph",
   "description": "For OSD hosts, this chart shows the latency at the physical drive. Each drive is shown by device name, with it's corresponding OSD id",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by(instance,device) (label_replace((irate(node_disk_write_time_seconds_total{ instance=~\"($ceph_hosts).*\"}[5m]) )  / clamp_min(irate(node_disk_writes_completed_total{ instance=~\"($ceph_hosts).*\"}[5m]), 0.001) or   (irate(node_disk_read_time_seconds_total{ instance=~\"($ceph_hosts).*\"}[5m]) )  / clamp_min(irate(node_disk_reads_completed_total{ instance=~\"($ceph_hosts).*\"}[5m]), 0.001), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\")) *  on(instance,device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation{instance=~\"($ceph_hosts).*\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\")",
     "legendFormat": "{{device}}({{ceph_daemon}})"
    }
   ]
  },
  {
   "title": "$ceph_hosts Disk utilization",
   "type": "graph",
   "description": "Show disk utilization % (util) of any OSD devices on the host by the physical device name and associated OSD id.",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percent", "label": "%Util" }
   ],
   "targets": [
    {
     "expr": "label_replace(((irate(node_disk_io_time_ms{instance=~\"($ceph_hosts).*\"}[5m]) / 10 ) or  irate(node_disk_io_time_seconds_total{instance=~\"($ceph_hosts).*\"}[5m]) * 100), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\") * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation{instance=~\"($ceph_hosts).*\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\")",
     "legendFormat": "{{device}}({{ceph_daemon}})"
    }
   ]
  }
 ]
}