{
 "title": "RBD Overview",
 "tags": [ "overview" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(ceph_rbd_write_ops[30s])))",
     "legendFormat": "Writes"
    },
    {
     "expr": "round(sum(irate(ceph_rbd_read_ops[30s])))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(ceph_rbd_write_bytes[30s])))",
     "legendFormat": "Write"
    },
    {
     "expr": "round(sum(irate(ceph_rbd_read_bytes[30s])))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(ceph_rbd_write_latency_sum[30s])) / sum(irate(ceph_rbd_write_latency_count[30s])))",
     "legendFormat": "Write"
    },
    {
     "expr": "round(sum(irate(ceph_rbd_read_latency_sum[30s])) / sum(irate(ceph_rbd_read_latency_count[30s])))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Highest IOPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, (sort((irate(ceph_rbd_write_ops[30s]) + on(image, pool, namespace) irate(ceph_rbd_read_ops[30s])))))"
    }
   ]
  },
  {
   "title": "Highest Throughput",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, sort(sum(irate(ceph_rbd_read_bytes[30s]) + irate(ceph_rbd_write_bytes[30s])) by (pool, image, namespace)))"
    }
   ]
  },
  {
   "title": "Highest Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    irate(ceph_rbd_write_latency_sum[30s]) / clamp_min(irate(ceph_rbd_write_latency_count[30s]), 1) +\n    irate(ceph_rbd_read_latency_sum[30s]) / clamp_min(irate(ceph_rbd_read_latency_count[30s]), 1)\n  ) by (pool, image, namespace)\n)"
    }
   ]
  }
 ]
}