---


# copy decriptors

- name: Creates /etc/kubernetes/kubeadm directory
  file: path=/etc/kubernetes/kubeadm/klovercloud/klovercloud_services  recurse=yes state=directory
  when: >
    groups['kube-master'].index(inventory_hostname) == 0  


- name: Copy descriptors
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
     - { src: 'step.1.klovercloud-ci.v1.1.0.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.1.klovercloud-ci.v1.1.0.yaml'  } 
     - { src: 'step.2.klovercloud-harbor.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.2.klovercloud-harbor.yaml'  } 
     - { src: 'step.3.listener.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.3.listener.yaml'  } 
     - { src: 'step.4.management.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.4.management.yaml'  } 
     - { src: 'step.5.facade.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.5.facade.yaml'  } 
     - { src: 'step.6.pipeline.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.6.pipeline.yaml'  } 
     - { src: 'step.7.monitor.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.7.monitor.yaml'  } 
     - { src: 'step.8.klovercloud-database.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.8.klovercloud-database.yaml'  } 
     - { src: 'step.9.dns_manager.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.9.dns_manager.yaml'  }
     - { src: 'step.10.log_manager.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.10.log_manager.yaml'  }
     - { src: 'step.11.metrics.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.11.metrics.yaml'  } 
     - { src: 'step.12.my_store.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.12.my_store.yaml'  } 
     - { src: 'step.13.object_storage.yaml.j2', dest: '/etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.13.object_storage.yaml'  } 
  when: >
    groups['kube-master'].index(inventory_hostname) == 0  
  register: result


# deploy klovercloud-ci

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.1.klovercloud-ci.v1.1.0.yaml;
  when: >
    groups['kube-master'].index(inventory_hostname) == 0   
  ignore_errors: yes


- name: wait for pods to come up
  shell:  kubectl get pods -l app={{ klovercloud_ci_app_label }} -n {{ klovercloud_ci_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  ignore_errors: yes

- name: 
  wait_for:
    timeout: 20

- name: wait for pods to come up
  shell:  kubectl get pods -l app={{ klovercloud_ci_app_label }} -n {{ klovercloud_ci_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  


# deploy klovercloud harbor


- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.2.klovercloud-harbor.yaml;
  when: >
    groups['kube-master'].index(inventory_hostname) == 0   


- name: wait for pods to come up
  shell: kubectl get pods -l app={{ klovercloud_harbor_deployement_app_label }} -n {{ klovercloud_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  ignore_errors: yes

- name: 
  wait_for:
    timeout: 10

- name: wait for pods to come up
  shell: kubectl get pods -l app={{ klovercloud_harbor_deployement_app_label }} -n {{ klovercloud_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  ignore_errors: yes

# deploy listener

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.3.listener.yaml;
  when: >
    groups['kube-master'].index(inventory_hostname) == 0 


- name: wait for pods to come up
  shell: kubectl get pods -l app={{ klovercloud_listener_app_label }} -n {{ klovercloud_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  ignore_errors: yes

- name: 
  wait_for:
    timeout: 30

- name: wait for pods to come up
  shell: kubectl get pods -l app={{ klovercloud_listener_app_label }} -n {{ klovercloud_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  ignore_errors: yes

- name: Login to listener service as admin user
  shell: kubectl -n {{ klovercloud_namespace }} exec -it $(kubectl -n {{ klovercloud_namespace }} get pod -l "app={{ klovercloud_listener_app_label }}" -o jsonpath='{.items[0].metadata.name}') -- bin/sh -c "curl -X POST 'http://localhost:8080/api/auth/login'  -H 'Content-Type:application/json'  -d '{\"username\":\"NPHOgToi\",\"password\":\"onhZruhF\"}'"
  register: login_result


- debug:
    msg: logi_result= {{ login_result }}


- name: Create an API Access Token when login request returns token
  shell: kubectl -n {{ klovercloud_namespace }} exec -it $(kubectl -n {{ klovercloud_namespace }} get pod -l "app={{ klovercloud_listener_app_label }}" -o jsonpath='{.items[0].metadata.name}') -- bin/sh -c "curl -X POST 'http://localhost:8080/api/api-access-token'  -H 'Content-Type:application/json,x-auth-token:{{ login_result }}.json.token'"
  register: api_access_token

# - name: Create an API Access Token when login request returns token
#   uri:
#     url: http://{{klovercloud_listener_ingress_host}}/api/api-access-token
#     method: POST
#     return_content: yes
#     status_code: 200
#     body_format: json
#     headers:
#       Content-Type: "application/json"
#       x-auth-token: login_result.json.token
#   register: api_access_token
#   when: login_result.json.success == true

- debug:
    msg: api_access_token= {{ api_access_token }}


- name: reset klovercloud_api_access_token
  set_fact:
    klovercloud_api_access_token: api_access_token.json.data
  when: api_access_token.json.success == true


# deploy management

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.4.management.yaml;
  when: >
    groups['kube-master'].index(inventory_hostname) == 0

- name: wait for pods to come up
  shell: kubectl get pods -n {{ klovercloud_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]

- name: 
  wait_for:
    timeout: 10

# deploy facade


- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.5.facade.yaml;
  when: >
    groups['kube-master'].index(inventory_hostname) == 0


- name: wait for pods to come up
  shell: kubectl get pods -l app={{ klovercloud_facade_app_label }} -n {{ klovercloud_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  ignore_errors: yes

- name: 
  wait_for:
    timeout: 10

- name: wait for pods to come up
  shell: kubectl get pods -l app={{ klovercloud_facade_app_label }} -n {{ klovercloud_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  ignore_errors: yes

- name: Login to facade service as super admin user
  uri:
    url: https://{{klovercloud_facade_host}}/api/auth/login
    method: POST
    return_content: yes
    status_code: 200
    body_format: json
    headers:
      Content-Type: "application/json" 
    body: "{ \"username\": \"{{ klovercloud_super_admin_username }}\",\"password\": \"{{ klovercloud_super_admin_password }}\"}"
  register: facade_login_result
  until: facade_login_result.json.success == true
  retries: 10
  delay: 10

- name: Request to create a Service User using facade login token
  uri:
    url: http://{{klovercloud_facade_host}}/api/user
    method: POST
    return_content: yes
    status_code: 200
    body_format: json
    headers:
      Content-Type: "application/json"
      x-auth-token: facade_login_result.json.token
    body: "{ \"firstName\": \"{{klovercloud_service_firstname}}\",\"lastName\": \"{{klovercloud_service_lastname}}\",\"username\": \"{{ klovercloud_service_username }}\",\"userType\": \"{{ klovercloud_service_usertype }}\",\"authorities\": [ \"ROLE_AGENT_SERVICE\"]}"
  register: service_user
  when: facade_login_result.json.success == true

- name: Request to create a facade Service access token
  uri:
    url:  http://{{klovercloud_facade_host}}/api/api-access-token
    method: POST
    return_content: yes
    status_code: 200
    body_format: json
    headers:
      Content-Type: "application/json"
      x-auth-token: facade_login_result.json.token
    body:  "{ \"userId\": \"{{ service_user.json.data }}\"}" 
  register: facade_api_access_token
  when: service_user.json.success == true

- name: reset klovercloud_facade_api_access_token
  set_fact:
    klovercloud_facade_api_access_token: facade_api_access_token.json.data
  when: facade_api_access_token.json.success == true
  
- name: wait for pods to come up
  shell: kubectl get pods -n {{ klovercloud_namespace }} -o json
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]


# deploy pipeline

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.6.pipeline.yaml;
  when: >
     groups['kube-master'].index(inventory_hostname) == 0 

# deploy monitor 

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.7.monitor.yaml;
  when: >
     groups['kube-master'].index(inventory_hostname) == 0 

# deploy klovercloud-database 

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.8.klovercloud-database.yaml;
  when: >
     groups['kube-master'].index(inventory_hostname) == 0 

# deploy dns_manager 

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.9.dns_manager.yaml;
  when: >
     groups['kube-master'].index(inventory_hostname) == 0


# deploy log_manager

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.10.log_manager.yaml;
  when: >
     groups['kube-master'].index(inventory_hostname) == 0


# deploy metrics

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.11.metrics.yaml;
  when: >
     groups['kube-master'].index(inventory_hostname) == 0

# Create my_store service and ingress 

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.12.my_store.yaml;
  when: >
     groups['kube-master'].index(inventory_hostname) == 0

# Create rados admin user

- name: 
  shell: kubectl -n {{ klovercloud_rook_ceph_namespace }} exec -it $(kubectl -n {{ klovercloud_rook_ceph_namespace }} get pod -l "app=rook-ceph-tools" -o jsonpath='{.items[0].metadata.name}') -- bash -c 'radosgw-admin user create --uid={{ klovercloud_rook_ceph_object_storage_user_id }} --display-name={{ klovercloud_rook_ceph_object_storage_user_display_name }} --access-key={{ klovercloud_rook_ceph_object_storage_access_key }} --secret-key={{ klovercloud_rook_ceph_object_storage_secret_key }} &&  radosgw-admin --id admin caps add --caps="buckets=*;users=*;usage=*;metadata=*" --uid={{ klovercloud_rook_ceph_object_storage_user_id }}'

# Deploy object storage 

- name:  
  shell: kubectl apply -f /etc/kubernetes/kubeadm/klovercloud/klovercloud_services/step.13.object_storage.yaml;
  when: >
     groups['kube-master'].index(inventory_hostname) == 0