docker_ce_ubuntu: 18.06.2~ce~3-0~ubuntu
docker_ce_redhat: 18.09.9
containerd: 1.2.10

ubunutu_k8_version: 1.15.6-00
redhat_k8_version: 1.15.10-0

##### nginx ingress ########
nginx_ingress_controller_version: 0.29.0
nginx_ingress_controller_replicas: 2
ingress_hostname: www.klovercloud.com
nginx_ingress_http: 30080
nginx_ingress_https: 30443
nginx_ingress_http_mgmt: 18080
kube_master_lb: 10.20.0.13
kube_master_lb: 10.20.0.13


### monitoring ####
cortex_endpoint: http://cortex-nginx.cortex.svc.cluster.local:80/api/prom/push

###### cassandra #######
cassandra_replicas: 3
cassandra_taint: cassandra 
cassandra_version: v13
cassandra_password: admin1234

####### cortex #####
cortex_version: v0.4.0
cortex_date: 2017-03-01
cortex_taint: storage
cortex_cassandra: cassandra.cassandra.svc.cluster.local
cortex_ingester: 3
cortex_querier: 3
cortex_distributor: 1
cortex_queryfrontend: 2
cortex_nginx: 1

