profile: dev
kube_master_lb: 10.20.0.8

docker_ce_ubuntu: 18.06.2~ce~3-0~ubuntu

docker_ce_redhat: 19.03.8
containerd: 1.2.13

ubunutu_k8_version: 1.15.6-00
redhat_k8_version: 1.16.8-0  

##### nginx ingress ########
nginx_ingress_controller_version: 0.29.0
nginx_ingress_controller_replicas: 2
ingress_hostname: www.klovercloud.com
nginx_ingress_http_mgmt: 18080
ingress_limit_cpu: 1000m
ingress_limit_mem: 2Gi
ingress_request_cpu: 1000m
ingress_request_mem: 2Gi


### monitoring ####
cortex_endpoint: http://cortex-nginx.cortex.svc.cluster.local:80/api/prom/push
prometheus_retention_time: 2d
prometheus_image: v2.16.0
prometheus_pvc: 8Gi
monitoring_alertmanager: v0.20.0
monitoring_alertmanager_pvc: 2Gi
monitoring_node_exporter: v0.18.1
monitoring_kube_state_metrics: v1.9.5
monitoring_pushgateway: v1.0.1

####### Ceph ######
ceph_mon: 3
osdsPerDevice: 1 # number of OSD per device 
ceph_version: v14.2.7
rbdMirroring: 3
storage_taint: storage

###### cassandra #######
cassandra_endpoint:  cassandra.cassandra.svc.cluster.local
cassandra_replicas: 3
cassandra_storage: 5Gi
cassandra_strorage_class: rook-ceph-block-ec
cassandra_taint: storage 
cassandra_password: admin1234
cassandra_limit_cpu: 1000m
cassandra_limit_mem: 500Mi
cassandra_request_cpu: 1000m
cassandra_request_mem: 500Mi
cassandra_max_heap_size: 256M
cassandra_heap_newsize: 100M


####### cortex #####
cortex_version: v0.4.0
cortex_date: 2017-04-01
cortex_chunk_start_day: 2020-04-10
cortex_taint: storage
cortex_cassandra: cassandra.cassandra.svc.cluster.local

cortex_memcached_replica: 1
cortex_memcached_index_read_replica: 1
cortex_memcached_index_write_replica: 1
cortex_memcached_limit_cpu: 500m
cortex_memcached_limit_mem: 1Gi
cortex_memcached_req_cpu: 500m
cortex_memcached_req_mem: 1Gi 

cortex_ingester_replica: 3
cortex_ingester_limit_cpu: 1000m
cortex_ingester_limit_mem: 1Gi
cortex_ingester_req_cpu: 1000m
cortex_ingester_req_mem: 1Gi 

cortex_distributor_replica: 1
cortex_distributor_limit_cpu: 1000m
cortex_distributor_limit_mem: 1Gi
cortex_distributor_req_cpu: 1000m
cortex_distributor_req_mem: 1Gi

cortex_querier_replica: 1
cortex_querier_limit_cpu: 1000m
cortex_querier_limit_mem: 1Gi
cortex_querier_req_cpu: 1000m
cortex_querier_req_mem: 1Gi 

cortex_query_frontend_replica: 1
cortex_queryfrontend_limit_cpu: 1000m
cortex_queryfrontend_limit_mem: 1Gi
cortex_queryfrontend_req_cpu: 1000m
cortex_queryfrontend_req_mem: 1Gi 

cortex_nginx_replica: 1
cortex_nginx_limit_cpu: 500m
cortex_nginx_limit_mem: 500Mi
cortex_nginx_req_cpu: 500m
cortex_nginx_req_mem: 500Mi 

cortex_nginx: 1


#### promtail ####
loki_gateway_url: http://gateway.loki.svc/loki/api/v1/push

####### loki #####
loki_version: v0.4.0
loki_date: 2017-04-01
loki_chunk_start_day: 2020-04-01
loki_taint: storage
loki_cassandra: cassandra.cassandra.svc.cluster.local

loki_memcached_replica: 1
loki_memcached_frontend_replica: 1
loki_memcached_index_queries_replica: 1
loki_memcached_index_writes_replica: 1
loki_memcached_limit_cpu: 500m
loki_memcached_limit_mem: 1Gi
loki_memcached_req_cpu: 500m
loki_memcached_req_mem: 1Gi

loki_ingester_replica: 3
loki_ingester_limit_cpu: 1000m
loki_ingester_limit_mem: 1Gi
loki_ingester_req_cpu: 1000m
loki_ingester_req_mem: 1Gi

loki_distributor_replica: 1
loki_distributor_limit_cpu: 1000m
loki_distributor_limit_mem: 1Gi
loki_distributor_req_cpu: 1000m
loki_distributor_req_mem: 1Gi

loki_querier_replica: 1
loki_querier_limit_cpu: 1000m
loki_querier_limit_mem: 1Gi
loki_querier_req_cpu: 1000m
loki_querier_req_mem: 1Gi

loki_query_frontend_replica: 1
loki_queryfrontend_limit_cpu: 1000m
loki_queryfrontend_limit_mem: 1Gi
loki_queryfrontend_req_cpu: 1000m
loki_queryfrontend_req_mem: 1Gi

loki_nginx_replica: 1
loki_nginx_limit_cpu: 500m
loki_nginx_limit_mem: 500Mi
loki_nginx_req_cpu: 500m
loki_nginx_req_mem: 500Mi

