---
apiVersion: v1
data:
  nginx.conf: |
    worker_processes  5;  ## Default: 1
    error_log  /dev/stderr;
    pid        /tmp/nginx.pid;
    worker_rlimit_nofile 8192;
    events {
      worker_connections  4096;  ## Default: 1024
    }
    http {
      default_type application/octet-stream;
      log_format   main '$remote_addr - $remote_user [$time_local]  $status '
        '"$request" $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log   /dev/stderr  main;
      sendfile     on;
      tcp_nopush   on;
      resolver kube-dns.kube-system.svc.cluster.local;
      server {
        listen               80;
        #auth_basic           “Prometheus”;
        #auth_basic_user_file /etc/nginx/secrets/.htpasswd;
        proxy_set_header     X-Scope-OrgID 1;
        location = /api/prom/push {
          proxy_pass       http://distributor.loki.svc.cluster.local$request_uri;
        }
        location = /api/prom/tail {
          proxy_pass       http://querier.loki.svc.cluster.local$request_uri;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }
        location ~ /api/prom/.* {
          proxy_pass       http://query-frontend.loki.svc.cluster.local$request_uri;
        }
        location = /loki/api/v1/push {
          proxy_pass       http://distributor.loki.svc.cluster.local$request_uri;
        }
        location = /loki/api/v1/tail {
          proxy_pass       http://querier.loki.svc.cluster.local$request_uri;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }
        location ~ /loki/api/.* {
          proxy_pass       http://query-frontend.loki.svc.cluster.local$request_uri;
        }
      }
    }
kind: ConfigMap
metadata:
  name: gateway-config
---
apiVersion: v1
data:
  .htpasswd: bG9raTokYXByMSRINHlHaUdOZyRzc2w1L055bWFHRlJVdnhJVjFOeXIu
kind: Secret
metadata:
  name: gateway-secret
type: Opaque

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: gateway
  name: gateway
spec:
  ports:
  - name: nginx-http
    port: 80
    targetPort: 80
  selector:
    name: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  minReadySeconds: 10
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: gateway
  template:
    metadata:
      labels:
        name: gateway
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                name: gateway
            topologyKey: kubernetes.io/hostname
      containers:
      - image: nginx:1.15.1-alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        volumeMounts:
        - mountPath: /etc/nginx
          name: gateway-config
        #- mountPath: /etc/nginx/secrets
        #  name: gateway-secret
      volumes:
      - configMap:
          name: gateway-config
        name: gateway-config
      - name: gateway-secret
        secret:
          defaultMode: 420
          secretName: gateway-secret

