---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: query-frontend
  name: query-frontend
spec:
  clusterIP: None
  ports:
  - name: query-frontend-http-metrics
    port: 80
    targetPort: 80
  - name: query-frontend-grpc
    port: 9095
    targetPort: 9095
  selector:
    name: query-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-frontend
spec:
  minReadySeconds: 10
  replicas: {{ loki_query-frontend_replica }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: query-frontend
  template:
    metadata:
      annotations:
        config_hash: 4f80cdaf0db655fa4b3b3cd15c0a0f44
      labels:
        name: query-frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                name: query-frontend
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - -config.file=/etc/loki/config/config.yaml
        #- -limits.per-user-override-config=/etc/loki/overrides/overrides.yaml
        #- -log.level=debug
        - -target=query-frontend
        image: grafana/loki:v1.3.0
        imagePullPolicy: IfNotPresent
        name: query-frontend
        ports:
        - containerPort: 80
          name: http-metrics
        - containerPort: 9095
          name: grpc
{% if profile  == "prod" %}

        resources:
          limits:
           memory: 1200Mi
         requests:
           cpu: "2"
          memory: 600Mi
{% endif %}

        olumeMounts:
        - mountPath: /etc/loki/config
          name: loki
        - mountPath: /etc/loki/overrides
          name: overrides
      volumes:
      - configMap:
          name: loki
        name: loki
      - configMap:
          name: overrides
        name: overrides
