# common
klovercloud_super_admin_username: admin-listener@klovercloud.com
klovercloud_super_admin_password: hello123
klovercloud_super_admin_secret: klovercloud-super-admin-secret
klovercloud_dns_manager_service: klovercloud-dns-manager
klovercloud_log_manager_service: klovercloud-log-manager
klovercloud_default_ingress_domain: klovercloud.com
klovercloud_developer_alias: klovercloud
klovercloud_namespace: klovercloud
klovercloud_api_access_token: abcxyz
klovercloud_image_pulling_secret: regcred-harbor

klovercloud_registry_username: klover-dev
klovercloud_registry_password: Dev@Klover2019!
klovercloud_registry_email: shihab.hasan@klovercloud.com
klovercloud_service_username: klovercloud-service-user@klovercloud.com
klovercloud_service_lastname: user
klovercloud_service_firstname: klovercloud service
klovercloud_service_usertype: AGENT_SERVICE
klovercloud_service_authorities: ROLE_AGENT_SERVICE

# Klovercloud-ci
klovercloud_ci_namespace: tekton
klovercloud_ci_replica: 1
klovercloud_ci_cpu_request: 500m
klovercloud_ci_memory_request: 1024Mi
klovercloud_ci_cpu_limit: 1000m
klovercloud_ci_memory_limit: 1536Mi
klovercloud_ci_containers_port: 8084
klovercloud_ci_tecknology: TEKTON

klovercloud_ci_image: container-registry.klovercloud.com/klovercloud/klovercloud-ci:1.1.0
klovercloud_ci_mongo_service_name: mongodb-internal-kc
klovercloud_ci_mongo_external_name: mongodb.klovercloud.svc.cluster.local
klovercloud_ci_db_connection_str: mongodb://mongoAdmin:abc123@mongodb-internal-kc:27017
klovercloud_ci_db_name: klovercloud_ci

klovercloud_ci_facade_service_url: klovercloud-facade-internal-kc/web-socket-ns
klovercloud_ci_facade_service_access_token: 925a05d796362ba0617d241a72c977844f72cc768c491d74410cecb496ae2615TEFyBAkAw6
klovercloud_ci_facade_service_name: klovercloud-facade-internal-kc
klovercloud_ci_facade_service_external_name: klovercloud-facade.klovercloud.svc.cluster.local
klovercloud_ci_facade_port: 80

klovercloud_ci_pipeline_service_url: http://klovercloud-pipeline-internal-kc
klovercloud_ci_pipeline_service_name: klovercloud-pipeline-internal-kc
klovercloud_ci_pipeline_service_external_name: klovercloud-pipeline.klovercloud.svc.cluster.local
klovercloud_ci_pipeline_service_port: 80

klovercloud_ci_nexus_token: YWRtaW46YWRtaW4=
klovercloud_ci_nexus_username: admin
klovercloud_ci_nexus_password: admin
klovercloud_ci_nexus_maven_public_url: http://nexus.klovercloud.com/repository/maven-public/
klovercloud_ci_nexus_maven_releases_url: http://nexus.klovercloud.com/repository/maven-releases/
klovercloud_ci_nexus_maven_snapshot_url: http://nexus.klovercloud.com/repository/maven-snapshot/
klovercloud_ci_nexus_npm_group_url: http://nexus.klovercloud.com/repository/npm-group/

klovercloud_ci_service_name: klovercloud-ci
klovercloud_ci_service_port: 80
klovercloud_ci_app_label: klovercloud-ci
klovercloud_ci_deployment_name: klovercloud-ci
klovercloud_ci_service_account_name: klovercloud-ci

# klovercloud mongodb 
klovercloud_mongodb_replica: 1
klovercloud_mongodb_storage: 2000Mi
klovercloud_mongodb_cpu_request: 500m
klovercloud_mongodb_memory_request: 500Mi
klovercloud_mongodb_cpu_limit: 1000m
klovercloud_mongodb_memory_limit: 1000Mi
klovercloud_mongodb_containers_port: 27017
klovercloud_mongodb_metrics_cpu_request: 100m
klovercloud_mongodb_metrics_memory_request: 128Mi
klovercloud_mongodb_metrics_cpu_limit: 200m
klovercloud_mongodb_metrics_memory_limit: 256Mi
klovercloud_mongodb_metrics_container_port: 9216

klovercloud_mongdb_app_label: mongodb-server
klovercloud_mongodb_statefulset_name: mongodb
klovercloud_mongodb_nodeport_service_name: mongodb-nodeport

klovercloud_mongodb_service_name: mongodb
klovercloud_mongodb_service_port: 27017
klovercloud_mongodb_service_target_port: 27017
klovercloud_mongodb_metrics_port: 9216
klovercloud_mongodb_metrics_target_port: 9216
klovercloud_mongodb_service_node_port: 32205
klovercloud_mongodb_metrics_node_port: 32206
klovercloud_mongodb_image: docker.io/bitnami/mongodb:4.2.3-debian-10-r31
klovercloud_mongodb_exporter_image: docker.io/bitnami/mongodb-exporter:0.10.0-debian-10-r27
klovercloud_mongodb_replica_set_key: admin123
klovercloud_mongodd_root_password: admin123
klovercloud_mongo_auth_db_name: admin
klovercloud_mongo_root_username: root

# klovercloud kafka
klovercloud_kafka_replica: 1
klovercloud_kafka_io_kompose_service: kafka
klovercloud_kafka_data_io_kompose_service: kafka-data
klovercloud_kafka_service_name: kafka
klovercloud_kafka_statefulset_name: kafka
klovercloud_kafka_app_label: kafka
klovercloud_kafka_container_port: 9092
klovercloud_kafka_target_port: 9092
klovercloud_kafka_service_port: 9092
klovercloud_kafka_image: bitnami/kafka:latest
klovercloud_kafka_storage: 2Gi

klovercloud_zookeeper_replica: 1
klovercloud_zookeeper_io_kompose_service: zookeeper
klovercloud_zookeeper_data_io_kompose_service: zookeeper-data
klovercloud_zookeeper_service_name: zookeeper
klovercloud_zookeeper_deployment_name: zookeeper
klovercloud_zookeeper_image: bitnami/zookeeper:latest
klovercloud_zookeeper_container_port: 2181
klovercloud_zookeeper_service_port: 2181
klovercloud_zookeeper_target_port: 2181
klovercloud_zookeeper_storage: 2Gi

# klovercloud nexus
klovercloud_nexus_namespace: nexus
klovercloud_nexus_replica: 1
klovercloud_nexus_storage: 2000Mi
klovercloud_nexus_cpu_request: 500m
klovercloud_nexus_memory_request: 2Gi
klovercloud_nexus_cpu_limit: 1000m
klovercloud_nexus_memory_limit: 4Gi
klovercloud_nexus_default_super_admin_password: abc
klovercloud_nexus_super_admin: admin
klovercloud_nexus_super_admin_password: admin
klovercloud_nexus_operator_name: nexus-operator
klovercloud_nexus_operator_image: zeromsi2/nexus

klovercloud_nexus_operator_role_name: nexus-operator
klovercloud_nexus_operator_role_binding_name: nexus-operator
klovercloud_nexus_operator_service_account_name: nexus-operator
klovercloud_nexus_operator_service_name: klovercloud-nexus
klovercloud_nexus_operator_service_port: 8081

klovercloud_nexus_cr: example-nexus
klovercloud_nexus_app_label: nexus

klovercloud_nexus_ingress_name: klovercloud-nexus
klovercloud_nexus_ingress_host: nexus.klovercloud.com


# Listener
klovercloud_listener_replica: 1
klovercloud_listener_cpu_request: 350m
klovercloud_listener_memory_request: 512Mi
klovercloud_listener_cpu_limit: 1000m
klovercloud_listener_memory_limit: 1000Mi
klovercloud_listener_deployment_name: klovercloud-listener
klovercloud_listener_app_label: klovercloud-listener
klovercloud_listener_image: container-registry.klovercloud.com/klovercloud/klovercloud-listener:latest
klovercloud_listener_container_port1: 8080
klovercloud_listener_container_port2: 8081
klovercloud_listener_service_port: 80
klovercloud_listener_target_port: 8080
klovercloud_listener_service_name: klovercloud-listener
klovercloud_listener_metrics_sevice_port: 80
klovercloud_listener_metrics_sevice_target_port: 8080
klovercloud_listener_ingress_name: klovercloud-listener
klovercloud_listener_ingress_host: listener.klovercloud.com


# Cert Issuer
klovercloud_cert_issuer_name: letsencrypt-prod
acme_server: https://acme-v02.api.letsencrypt.org/directory
acme_email: user@klovercloud.com
private_key_secret_ref_name: letsencrypt-prod


# Management 
klovercloud_management_replica: 1
klovercloud_management_cpu_request: 500m
klovercloud_management_memory_request: 512Mi
klovercloud_management_cpu_limit: 750m
klovercloud_management_memory_limit: 786Mi
klovercloud_management_deployment_name: klovercloud-management
klovercloud_management_service_name: klovercloud-management
klovercloud_management_image: container-registry.klovercloud.com/klovercloud/klovercloud-management:latest
klovercloud_management_app_label: klovercloud-management
klovercloud_management_cluster_resource_limit_factor_cpu: 0.6
klovercloud_management_cluster_resource_limit_factor_memory: 0.8
klovercloud_management_cluster_resource_limit_factor_storage: 0.6
klovercloud_management_container_port1: 8080
klovercloud_management_container_port2: 8081
klovercloud_management_service_port: 80
klovercloud_management_target_port: 80
klovercloud_management_metrics_port: 80
klovercloud_management_metrics_target_port: 80
klovercloud_management_ci_service_name: klovercloud-ci-internal-kc
klovercloud_management_ci_external_service_name: klovercloud-ci.tekton.svc.cluster.local
klovercloud_management_ci_service_port: 80

# Facade
klovercloud_facade_replica: 1
klovercloud_facade_deployment_name: klovercloud-facade
klovercloud_facade_service_name: klovercloud-facade
klovercloud_facade_ingress_name: klovercloud-facade
klovercloud_facade_app_label: klovercloud-facade
klovercloud_facade_cpu_request: 500m
klovercloud_facade_memory_request: 778Mi
klovercloud_facade_cpu_limit: 750m
klovercloud_facade_memory_limit: 1024Mi
klovercloud_facade_container_port1: 8080
klovercloud_facade_container_port2: 8081
klovercloud_facade_service_port: 80
klovercloud_facade_target_port: 8080
klovercloud_facade_metrics_port: 8081
klovercloud_facade_metrics_target_port: 8081
klovercloud_facade_tls_secret: facade-tls
klovercloud_facade_host: facade.klovercloud.com
klovercloud_facade_admin_username: admin@klovercloud.com
klovercloud_facade_admin_password: hello123
klovercloud_facade_image: container-registry.klovercloud.com/klovercloud/klovercloud-facade:latest
klovercloud_facade_api_access_token: abcxyz

#pipeline
klovercloud_pipeline_replica: 1
klovercloud_pipeline_deployment_name: klovercloud-pipeline
klovercloud_pipeline_app_label: klovercloud-pipeline
klovercloud_pipeline_service_name:  klovercloud-pipeline-internal-kc
klovercloud_pipeline_image: container-registry.klovercloud.com/klovercloud/klovercloud-pipeline:latest

klovercloud_pipeline_cpu_request: 500m
klovercloud_pipeline_memory_request: 756Mi
klovercloud_pipeline_cpu_limit: 1000m
klovercloud_pipeline_memory_limit: 1024Mi

klovercloud_pipeline_container_port1: 8080
klovercloud_pipeline_container_port2: 8081