---

- name: Creates /var/tmp/k8/grafana  directory
  file: path=/var/tmp/k8/grafanai/dash  recurse=yes state=directory
  when: >
    groups['kube_master'].index(inventory_hostname) == 0 

- name: Copy monitoring config files
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
     - { src: 'metrics-connection.yaml.j2', dest: '/var/tmp/k8/grafana/metrics-connection.yaml'  }  
     - { src: 'grafana.yaml.j2', dest: '/var/tmp/k8/grafana/grafana.yaml'  }  
  when: >
    groups['kube_master'].index(inventory_hostname) == 0 
  register: result

- name:  create monitoring namespace
  shell: kubectl create ns monitoring;
  when: >
    groups['kube_master'].index(inventory_hostname) == 0 
  ignore_errors: yes

- name: copy dashboard file 
  copy:
    src: "{{ item }}"  
    dest: /var/tmp/k8/grafana/dash/ 
  with_fileglob:
    - roles/monitoring_grafana/templates/dashboard/dash*.yaml

- name: create monitoring 
  shell:  kubectl apply -n monitoring -f /var/tmp/k8/grafana/dash
         # kubectl apply -n monitoring -f /var/tmp/k8/grafana/metrics-connection.yaml; \
         #kubectl apply -n monitoring -f /var/tmp/k8/grafana/grafana.yaml ;
  when: >
    groups['kube_master'].index(inventory_hostname) == 0 
  ignore_errors: yes
