{
 "title": "1 Kubernetes cluster overview",
 "description": "This dashboard shows SLO, error budget and can help troubleshooting issue in k8s cluster at cluster, node and namespace level.",
 "tags": [
  "kubernetes",
  "k8s",
  "namespace"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(kube_node_created,node)"
   },
   {
    "name": "namespace",
    "query": "query_result(kube_namespace_labels)"
   },
   {
    "name": "container",
    "query": "kube_pod_container_info{namespace=\"$namespace\"}"
   },
   {
    "name": "duration",
    "query": "10m,30m,1h,2h,6h,12h,1d,2d,5d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Cluster SLO and Error budget", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster control plane SLO over $duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(\navg_over_time((sum without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}) \n/ \ncount without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}))[$duration:5m])\n)"
    }
   ]
  },
  {
   "title": "Control plane error budget remaining over $duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "\n\n(( avg(avg_over_time((sum without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.etcd.*\"}) \n/ \ncount without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.etcd.*\"}))[$duration:5m])\n)) - 0.98999999999999999 ) \n* \navg((time() - timestamp(up{job=\"apiserver\",namespace=\"default\",service=\"kubernetes\"} offset $duration)))\n\n"
    }
   ]
  },
  {
   "title": "Promtheus monitoring SLO over $duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(\navg_over_time((sum without ()(kube_pod_status_ready{namespace=\"monitoring\",pod=\"prometheus-prometheus-operator-prometheus-0\",condition=\"true\"}) \n/ \ncount without ()(kube_pod_status_ready{namespace=\"monitoring\",pod=\"prometheus-prometheus-operator-prometheus-0\"}))[$duration:5m])\n)"
    }
   ]
  },
  {
   "title": "Overall cluster status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "cluster  node status",
     "type": "btplc-status-dot-panel",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 2 },
     "format": "none",
     "targets": [
      {
       "expr": "(kube_node_status_condition{status=\"true\",condition=\"Ready\"}) ",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Cluster age",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(time() - kube_service_created{namespace=\"default\",service=\"kubernetes\"})"
      }
     ]
    },
    {
     "title": "cluster  node details",
     "type": "table",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 2 },
     "targets": [
      { "expr": "cadvisor_version_info", "legendFormat": "{{node}}" }
     ]
    },
    {
     "title": "cluster node readiness",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kube_node_status_condition{status=\"true\",condition=\"Ready\"}) ",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Namespaces ",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 5, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": " count(kube_namespace_created)", "legendFormat": "{{pod}}" }
     ]
    },
    {
     "title": "Total pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 8, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": " count(count by (pod)(container_spec_memory_reservation_limit_bytes{pod!=\"\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Waiting pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_pod_container_status_waiting !=0 ) or vector(0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Terminated pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 14, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_pod_container_status_terminated_reason{reason!=\"Completed\"} !=0 ) or vector(0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Waiting/Terminated pods",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by(namespace,reason) (kube_pod_container_status_terminated_reason{reason!=\"Completed\"} !=0 )",
       "legendFormat": "TERMINATED::{{reason}}::{{namespace}}"
      },
      {
       "expr": "count by(namespace,reason) (kube_pod_container_status_waiting_reason !=0 )",
       "legendFormat": "WAITING::{{reason}}::{{namespace}}"
      },
      {}
     ]
    },
    {
     "title": "PVCs",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 5, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_persistentvolumeclaim_info) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ReadOnly PVC",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 8, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_pod_spec_volumes_persistentvolumeclaims_readonly != 0) "
      }
     ]
    },
    {
     "title": "Besteffort  pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.besteffort.*\",id!~\".*.scope\",pod!=\"\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "burstable  pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 14, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.burstable.*\",id!~\".*.scope\",pod!=\"\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Node  wise load in cluster",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load5 + on(instance) group_left(nodename) \nnode_uname_info",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Memory usage in cluster",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{pod!=\"POD\",namespace!=\"\"})",
       "legendFormat": "Total memory used"
      },
      {
       "expr": "sum(kube_node_status_capacity{resource=\"memory\"})",
       "legendFormat": "Total memory"
      }
     ]
    },
    {
     "title": "Memory usage in cluster by node",
     "type": "graph",
     "description": "This panel shows node memory usage:\n\nnode_memory_MemTotal - node_memory_MemAvailable",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "((node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info) - (node_memory_MemAvailable_bytes  + on(instance) group_left(nodename) \nnode_uname_info))",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Memory usage by namespace in cluster",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "(sum by (namespace)(container_memory_usage_bytes{pod!=\"POD\",namespace!=\"\"}))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Overall CPU usage in cluster",
     "type": "graph",
     "description": "This panel shows node CPU utilisation",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(sum by (instance,nodename) (irate(node_cpu{mode!~\"guest.*|idle|iowait\"}[5m])) + on(instance) group_left(nodename) \nnode_uname_info)",
       "legendFormat": "Total Used CPU in cluster"
      },
      {
       "expr": "sum(kube_node_status_capacity{resource=\"cpu\"})",
       "legendFormat": "Total CPU in cluster"
      }
     ]
    },
    {
     "title": "Node CPU usage[5m] in cluster",
     "type": "graph",
     "description": "This panel shows node CPU utilisation",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (instance,nodename) (irate(node_cpu_seconds_total{mode!~\"guest.*|idle|iowait\"}[5m])) + on(instance) group_left(nodename) \nnode_uname_info)",
       "legendFormat": "{{nodename}} "
      }
     ]
    }
   ]
  },
  {
   "title": "$node Node details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": " (\n (sum(time() - node_boot_time_seconds + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"})) \nand \nON() kube_node_status_condition{status=\"true\",condition=\"Ready\",node=\"$node\"} == 1 \n)"
      }
     ]
    },
    {
     "title": "Node evictions",
     "type": "stat",
     "description": "Number of Node evictions that happened since current instance of NodeController started. Sampled every 60 seconds.\n",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(node_collector_evictions_number{pod=~\".*.$node.*\"})"
      },
      {
       "expr": "node_memory_Unevictable_bytes{node=\"$node\"}"
      }
     ]
    },
    {
     "title": "pod count",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": " count(count by (pod)(container_spec_memory_reservation_limit_bytes{node=\"$node\",pod!=\"\"}))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "besteffort pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.besteffort.*\",container=\"POD\",node=\"$node\"}))"
      }
     ]
    },
    {
     "title": "burstable pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{container=\"POD\",id=~\".*.burstable.*\",node=\"$node\"}))"
      }
     ]
    },
    {
     "title": "guaranteed pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{container=\"POD\",id!~\".*.burstable.*\",id!~\".*.besteffort.*\",node=\"$node\"}))"
      }
     ]
    },
    {
     "title": "Time synced",
     "type": "stat",
     "description": "Is clock synchronized to a reliable server (1 = yes, 0 = no). Sampled every 60 seconds.",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(node_timex_sync_status) * on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"} ",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Node readiness for  $node ",
     "type": "graph",
     "description": "This panel shows the NotReady state of nodes. If any node goes in NotReady state, graph value will go from 1 to 0.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kube_node_status_condition{status=\"true\",condition=\"Ready\",node=\"$node\"}) ",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "node $node Memory/Disk/PID Pressure",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kube_node_status_condition{status=\"true\",condition=~\"MemoryPressure|PIDPressure|DiskPressure\",node=\"$node\"})",
       "legendFormat": "{{condition}}"
      }
     ]
    },
    {
     "title": "Pod count by namespace on $node ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (namespace)(container_memory_working_set_bytes{image!=\"\",node=\"$node\"})",
       "legendFormat": "{{namespace}}"
      },
      {}
     ]
    },
    {
     "title": "Node $node load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load5 + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"}",
       "legendFormat": "{{nodename}}"
      },
      {
       "expr": "kube_node_status_capacity_cpu_cores{node=\"$node\"}",
       "legendFormat": "Total CPU"
      }
     ]
    },
    {
     "title": "Node $node CPU usage",
     "type": "graph",
     "description": "record: instance:node_cpu_utilisation:rate1m\nexpr: 1\n  - avg without(cpu, mode) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[1m]))",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "\n((sum by (instance) (instance:node_cpu_utilisation:rate1m)) + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"})",
       "legendFormat": "{{nodename}}"
      },
      {
       "expr": "kube_node_status_capacity{node=\"$node\",resource=\"cpu\"}",
       "legendFormat": "Total CPU"
      }
     ]
    },
    {
     "title": "Total CPU requests on $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (node)(kube_pod_container_resource_requests_cpu_cores{node=\"$node\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "kube_node_status_capacity{node=\"$node\",resource=\"cpu\"}",
       "legendFormat": "Total CPU"
      }
     ]
    },
    {
     "title": "Total CPU limits on $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (node)(kube_pod_container_resource_limits_cpu_cores{node=\"$node\"})",
       "legendFormat": "total limits"
      },
      {
       "expr": "kube_node_status_capacity{node=\"$node\",resource=\"cpu\"}",
       "legendFormat": "Total CPU"
      }
     ]
    },
    {
     "title": "Node $node memory usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"}) - (node_memory_MemAvailable_bytes  + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"})",
       "legendFormat": "{{nodename}}"
      },
      {
       "expr": "kube_node_status_capacity{node=\"$node\",resource=\"memory\"}",
       "legendFormat": "Total memory"
      }
     ]
    },
    {
     "title": "Total memory requests on $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (node)(kube_pod_container_resource_requests_memory_bytes{node=\"$node\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "kube_node_status_capacity{node=\"$node\",resource=\"memory\"}",
       "legendFormat": "Total memory"
      }
     ]
    },
    {
     "title": "Total Memory limits on $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (node)(kube_pod_container_resource_limits_memory_bytes{node=\"$node\"})",
       "legendFormat": "total liimits "
      },
      {
       "expr": "kube_node_status_capacity{node=\"$node\",resource=\"memory\"}",
       "legendFormat": "Total memory"
      }
     ]
    },
    {
     "title": "$node disk usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(sum by (instance,nodename,device) (node_filesystem_avail_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"$node\"}))",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Top 5  memory guzzling pods on $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": " sort(topk(5, container_memory_working_set_bytes{image!=\"\",node=\"$node\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "kubelet_runtime_operations_errors_total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kubelet_runtime_operations_errors_total{job=\"kubelet\",node=\"$node\"}[5m])) by (node, operation_type)",
       "legendFormat": "{{node}}: {{operation_type}}"
      }
     ]
    },
    {
     "title": "kubelet_pleg_relist_duration_seconds_bucket",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by (node,le) (rate(kubelet_pleg_relist_duration_seconds_bucket{node=\"$node\"}[5m])))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "node_timex_sync_status",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(node_timex_sync_status) * on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"} ",
       "legendFormat": "{{nodename}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace $namespace details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace $namespace SLO over $duration",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 4 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(\navg_over_time((sum without ()(kube_pod_container_status_ready{namespace=\"$namespace\"}) \n/ \ncount without ()(kube_pod_container_status_ready{namespace=\"$namespace\"}))[$duration:5m])\n)"
      }
     ]
    },
    {
     "title": "Error budget remaining for namespace: $namespace  over $duration",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 7, "y": 4 },
     "format": "s",
     "valueName": "avg",
     "targets": [
      {
       "expr": "\n\n(( avg(avg_over_time((sum without ()(kube_pod_container_status_ready{namespace=\"$namespace\"}) \n/ \ncount without ()(kube_pod_container_status_ready{namespace=\"$namespace\"}))[$duration:5m])\n)) - 0.98999999999999999 ) \n* \navg((time() - timestamp(up{job=\"apiserver\",namespace=\"default\",service=\"kubernetes\"} offset $duration)))\n\n"
      }
     ]
    },
    {
     "title": "total  pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{namespace=\"$namespace\",container=\"POD\"}))"
      }
     ]
    },
    {
     "title": "$namespace creation time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(time() - kube_namespace_created{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployments",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_deployment_created{namespace=\"$namespace\"})",
       "legendFormat": "{{deployment}}"
      }
     ]
    },
    {
     "title": "Ready pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_pod_container_status_ready{namespace=\"$namespace\"} !=0 ) or vector(0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Terminated pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_pod_container_status_terminated{namespace=\"$namespace\"} !=0 ) or vector(0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Waiting pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_pod_container_status_waiting{namespace=\"$namespace\"} !=0 ) or vector(0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "PVCs",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_persistentvolumeclaim_info{namespace=\"$namespace\"}) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "burstable  pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.burstable.*\",id!~\".*.scope\",pod!=\"\",namespace=\"$namespace\",container=\"POD\"}))"
      }
     ]
    },
    {
     "title": "Besteffort  pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.besteffort.*\",id!~\".*.scope\",pod!=\"\",namespace=\"$namespace\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Guaranteed  pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(container_spec_memory_reservation_limit_bytes{namespace=\"$namespace\",container=\"POD\",id!~\".*.burstable.*|.*.besteffort.*\",id!~\".*.scope\",pod!=\"\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod readiness in $namespace namespace",
     "type": "btplc-status-dot-panel",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
     "format": "none",
     "targets": [
      {
       "expr": "(kube_pod_container_status_ready{namespace=\"$namespace\"})",
       "legendFormat": "{{pod}}::{{container}}"
      }
     ]
    },
    {
     "title": "Total CPU usage in $namespace namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum\n  by(namespace) (rate(container_cpu_usage_seconds_total{container!=\"POD\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": " CPU usage by pod in $namespace namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum\n  by(pod) (rate(container_cpu_usage_seconds_total{container!=\"POD\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "pod count on nodes of $namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "count by (node)(kube_pod_info{namespace=\"$namespace\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Total memory  usage by pods in $namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum\n  by(namespace) (container_memory_usage_bytes{container!=\"POD\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\"})",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "memory  usage by pods in $namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 6, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum\n  by(pod) (container_memory_usage_bytes{container!=\"POD\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "persistentvolumeclaim status in namespace $namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "(kube_persistentvolumeclaim_access_mode{namespace=\"$namespace\"})",
       "legendFormat": "{{access_mode}}::{{persistentvolumeclaim}}"
      },
      {
       "expr": "kube_persistentvolumeclaim_status_phase{namespace=\"$namespace\",phase=\"Bound\"}",
       "legendFormat": "Bound::{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": " $namespace pods on $node",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "count by (pod)(container_memory_usage_bytes{namespace=\"$namespace\",node=\"$node\"})"
      }
     ]
    },
    {
     "title": "pod restarts in $namespace namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[2m]) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod  $container node relation",
     "type": "graph",
     "description": "This panel shows pod node relation",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kube_pod_info{namespace=\"$namespace\",pod=~\".*.$container.*\"})",
       "legendFormat": " {{node}}::  {{pod}}"
      }
     ]
    },
    {
     "title": "pod $container state in $namespace namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kube_pod_container_status_ready{namespace=\"$namespace\",container=\"$container\"}) ",
       "legendFormat": "READY::{{pod}}::container $container"
      },
      {
       "expr": "(kube_pod_container_status_waiting{namespace=\"$namespace\",container=\"$container\"})",
       "legendFormat": "WAITING::{{pod}}::container $container "
      },
      {
       "expr": "(kube_pod_container_status_terminated{namespace=\"$namespace\",container=\"$container\"})",
       "legendFormat": "TERMINATED::{{pod}}::container $container"
      }
     ]
    },
    {
     "title": "Resource Quota in namespace $namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kube_resourcequota{namespace=\"$namespace\",resource=~\".*.memory.*\"}/1024^3",
       "legendFormat": "{{type}}::{{resource}} GB"
      },
      {
       "expr": "kube_resourcequota{namespace=\"$namespace\",resource=~\".*.storage.*\"}/1024^3",
       "legendFormat": "{{type}}::{{resource}} GB"
      }
     ]
    },
    {
     "title": "pods running in $namespace",
     "type": "table",
     "gridPos": { "h": 18, "w": 18, "x": 6, "y": 37 },
     "targets": [
      {
       "expr": "kube_pod_info{namespace=\"$namespace\"}"
      }
     ]
    }
   ]
  }
 ]
}